import { ClerkProvider } from '@clerk/nextjs';
import { Inter } from "next/font/google";
import Header from './components/header';
import { dark } from '@clerk/themes'
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AI Flashcards - Haseebullah",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html lang="en">
        <body className={inter.className}  suppressHydrationWarning={true}>
          <Header />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
