import { ClerkProvider } from '@clerk/nextjs';
import { Inter } from "next/font/google";
import Header from './components/header';
import { dark } from '@clerk/themes'
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AI Flashcards - Haseebullah",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html lang="en">
        <body className={inter.className}  suppressHydrationWarning={true}>
          <Header />
          
          <main className="flex min-h-screen flex-col items-center pt-20 sm:pt-24 p-4 sm:px-24 bg-slate-900 text-slate-100">
            {children}
          </main>
          
        </body>
      </html>
    </ClerkProvider>
  );
}
